kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: group_id
    auto-offset-reset: earliest
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  listener:
    missing-topics-fatal: false
  admin:
    auto-create: true